In [2]:
import pandas as pd
pd.set_option('display.max_columns', 500)

In [2]:
gusto_eczema_old = pd.read_csv('data/gusto_eczema_edu12.csv')
print(gusto_eczema_old.shape)
gusto_rhinitis_old = pd.read_csv('data/gusto_rhinitis_edu12.csv')
print(gusto_rhinitis_old.shape)
gusto_wheeze_old = pd.read_csv('data/gusto_wheeze_edu12.csv')
print(gusto_wheeze_old.shape)

(1237, 42)
(1237, 42)
(1237, 42)

In [3]:
spresto_eczema_old = pd.read_csv('data/spresto_eczema_edu12.csv')
print(spresto_eczema_old.shape)
spresto_rhinitis_old = pd.read_csv('data/spresto_rhinitis_edu12.csv')
print(spresto_rhinitis_old.shape)
spresto_wheeze_old = pd.read_csv('data/spresto_wheeze_edu12.csv')
print(spresto_wheeze_old.shape)

(379, 42)
(379, 42)
(379, 42)

In [4]:
spresto_rhinitis_old.head()

,subject_id,eczema_cum,rhinitis_cum,wheeze_cum,ethnicity,delivery_age,highest_edu12,household_income,pc_vig,pc_mvpa,pg_vig,pg_mvpa,smoking_pg,passive_smoke_pc,passive_smoke_pg,delivery_mode,sex,ga,stai_state_pw26,stai_trait_pw26,stai_state_m3,stai_trait_m3,epds_tot_pw26,epds_tot_m3,infection_m3,alcohol_pc,alcohol_pg,parity,weight_birth,antibiotics_labour,antibiotics_m3,bisq_q3_m6,bisq_totslphrs_m6,bisq_q3_m12,bisq_totslphrs_m12,bf_m6,maternal_allergy_pw11,cat,dog,expressway,allergy_cum,rhinitis_label
0,10003,1.0,1.0,0.0,1.0,35.38,1.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,39.14,33.0,42.0,NaN,NaN,8.0,NaN,0.0,0.0,0.0,1.0,3.385,0.0,0.0,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0
1,10005,0.0,0.0,1.0,2.0,26.68,1.0,5.0,2.0,3.0,0.0,3.0,0.0,1.0,0.0,2.0,1.0,39.71,27.0,36.0,NaN,NaN,10.0,NaN,1.0,0.0,0.0,0.0,3.352,1.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,1.0,1.0,NaN
2,10006,NaN,NaN,NaN,3.0,NaN,0.0,5.0,0.0,3.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,10008,0.0,1.0,0.0,1.0,32.02,1.0,NaN,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,39.57,33.0,39.0,NaN,NaN,9.0,NaN,0.0,1.0,0.0,0.0,3.225,0.0,0.0,NaN,NaN,11.0,12.5,0.0,1.0,0.0,0.0,NaN,1.0,1.0
4,10009,0.0,0.0,0.0,1.0,36.56,1.0,NaN,NaN,NaN,0.0,1.0,0.0,NaN,0.0,1.0,1.0,39.29,25.0,42.0,NaN,NaN,9.0,NaN,0.0,0.0,0.0,NaN,3.224,0.0,0.0,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,0.0,0.0

In [13]:
colname_gusto = {"MPM3NEO": "neopterin", "MPM3RIBO": "riboflavin", "MPM3NIA": "nicotinicacid", "MPM3TRIG": "trigonelline", 
           "MPM3PY": "pyridoxal", "MPM3PLPB": "pyridoxalphosphate", "MPM3VD3": "vitamind3", "MPM3ARG": "arginine", 
           "MPM3ADMA": "adma", "MPM3CRN": "creatine", "MPM3CSTA": "cystathionine", "MPM3M3HS": "m3histidine", 
           "MPM3HIST": "histidine", "MPM3MET": "methionine", "MPM3HAA": "hydroxyanthralinicac", "MPM3KA": "kynurenicacid", 
           "MPM3KYN": "kynurenine", "MPM3TRP": "tryptophan", "MPM3BETN": "betaine", "MPM3CHOL": "choline", 
           "MPM3DMG": "dimethylglycine", "MPM3TMAO": "trimethylaminenoxide", "MPM3COT": "cotinine", 
           "MPM3C3HC": "hydroxycotinine", 'SubjectID': 'subject_id'}
colname_spresto = {"PGV4_Neopterin": "neopterin", "PGV4_Riboflavin": "riboflavin", "PGV4_Nicotinicacid": "nicotinicacid", 
                   "PGV4_Trigonelline": "trigonelline", "PGV4_Pyridoxal": "pyridoxal", 
                   "PGV4_Pyridoxalphosphate": "pyridoxalphosphate", "PGV4_VitaminD3": "vitamind3", "PGV4_Arginine": "arginine",
                     "PGV4_ADMA": "adma", "PGV4_Creatine": "creatine", "PGV4_Cystathionine": "cystathionine", 
                     "PGV4_m3Histidine": "m3histidine", "PGV4_Histidine": "histidine", "PGV4_Methionine": "methionine", 
                     "PGV4_Hydroxyanthralinicacid": "hydroxyanthralinicac", "PGV4_Kynurenicacid": "kynurenicacid", 
                     "PGV4_Kynurenine": "kynurenine", "PGV4_Tryptophan": "tryptophan", "PGV4_Betaine": "betaine", 
                     "PGV4_Choline": "choline", "PGV4_Dimethylglycine": "dimethylglycine", 
                     "PGV4_TrimethylamineNoxide": "trimethylaminenoxide", "PGV4_Cotinine": "cotinine", 
                     "PGV4_Hydroxycotinine": "hydroxycotinine", 'SubjectID': 'subject_id'}

In [14]:
gusto_bevital = pd.read_csv('data/gusto_bevital.csv')
gusto_bevital.rename(columns=colname_gusto, inplace=True)
print(gusto_bevital.shape)
gusto_bevital.head()

(1292, 25)

,subject_id,neopterin,riboflavin,nicotinicacid,trigonelline,pyridoxal,pyridoxalphosphate,vitamind3,arginine,adma,creatine,cystathionine,m3histidine,histidine,methionine,hydroxyanthralinicac,kynurenicacid,kynurenine,tryptophan,betaine,choline,dimethylglycine,trimethylaminenoxide,cotinine,hydroxycotinine
0,010-04002,15.6,23.80,0.0,0.2820,13.1,55.4,72.0,25.3,0.384,41.4,0.215,0.397,51.3,14.8,61.1,12.4,1.110,44.1,9.23,9.31,1.38,0.808,8.59,0.0
1,010-04004,27.7,6.24,0.0,0.3290,13.1,47.2,45.0,25.1,0.359,33.5,0.125,1.160,41.1,11.8,94.9,11.9,1.210,33.2,19.30,11.10,1.69,13.600,0.00,0.0
2,010-04006,32.4,9.92,0.0,0.4860,35.3,138.0,98.0,31.1,0.483,41.4,0.116,0.278,75.5,14.9,69.6,30.4,1.370,41.5,9.15,9.42,1.74,1.240,0.00,0.0
3,010-04010,12.3,17.30,0.0,0.1830,186.0,191.0,131.0,56.3,0.365,62.5,0.189,21.200,70.1,28.4,58.8,11.7,0.737,48.4,12.50,6.52,1.61,6.220,0.00,0.0
4,010-04011,19.8,12.00,0.0,0.0539,30.4,146.0,107.0,21.8,0.336,48.6,0.112,1.920,57.7,12.5,72.8,12.8,0.976,46.7,16.90,8.89,1.39,0.724,0.00,0.0

In [15]:
gusto_bevital.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1292 entries, 0 to 1291
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   subject_id            1292 non-null   object
 1   neopterin             980 non-null    float64
 2   riboflavin            980 non-null    float64
 3   nicotinicacid         980 non-null    float64
 4   trigonelline          980 non-null    float64
 5   pyridoxal             980 non-null    float64
 6   pyridoxalphosphate    980 non-null    float64
 7   vitamind3             944 non-null    float64
 8   arginine              980 non-null    float64
 9   adma                  980 non-null    float64
 10  creatine              980 non-null    float64
 11  cystathionine         980 non-null    float64
 12  m3histidine           980 non-null    float64
 13  histidine             980 non-null    float64
 14  methionine            980 non-null    float64
 15  hydroxyanthralinicac  980 non-null    float64
 16  kynurenicacid         980 non-null    float64
 17  kynurenine            980 non-null    float64
 18  tryptophan            980 non-null    float64
 19  betaine               980 non-null    float64
 20  choline               980 non-null    float64
 21  dimethylglycine       980 non-null    float64
 22  trimethylaminenoxide  980 non-null    float64
 23  cotinine              980 non-null    float64
 24  hydroxycotinine       980 non-null    float64
dtypes: float64(24), object(1)
memory usage: 252.5+ KB

In [16]:
spresto_bevital = pd.read_csv('data/spresto_bevital.csv')
spresto_bevital.rename(columns=colname_spresto, inplace=True)
print(spresto_bevital.shape)
spresto_bevital.head()

(985, 25)

,subject_id,neopterin,riboflavin,nicotinicacid,trigonelline,pyridoxal,pyridoxalphosphate,vitamind3,arginine,adma,creatine,cystathionine,m3histidine,histidine,methionine,hydroxyanthralinicac,kynurenicacid,kynurenine,tryptophan,betaine,choline,dimethylglycine,trimethylaminenoxide,cotinine,hydroxycotinine
0,10001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10003,10.8,105.0,0.00,0.11,37.80,137.0,110.89,28.5,0.39,57.9,0.12,1.93,63.4,16.2,70.1,17.3,0.81,49.6,10.2,8.57,1.29,1.16,0.0,0.0
3,10004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10005,20.2,100.0,0.97,0.03,4.05,15.8,57.93,33.1,0.42,34.8,0.17,1.42,63.1,21.3,96.3,14.2,1.23,44.2,14.8,8.51,1.92,0.89,0.0,0.0

In [18]:
gusto_eczema_new = pd.merge(gusto_eczema_old, gusto_bevital, how='left', on='subject_id')
gusto_eczema_new.info()
gusto_eczema_new.to_csv('data/gusto_eczema_v3.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1237 entries, 0 to 1236
Data columns (total 66 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   subject_id             1237 non-null   object
 1   eczema_cum             752 non-null    float64
 2   rhinitis_cum           838 non-null    float64
 3   wheeze_cum             731 non-null    float64
 4   ethnicity              1237 non-null   int64
 5   delivery_age           1171 non-null   float64
 6   highest_edu12          1220 non-null   float64
 7   household_income       1152 non-null   float64
 8   pc_vig                 1168 non-null   float64
 9   pc_mvpa                1170 non-null   float64
 10  pg_vig                 1165 non-null   float64
 11  pg_mvpa                1167 non-null   float64
 12  smoking_pg             1168 non-null   float64
 13  passive_smoke_pc       1135 non-null   float64
 14  passive_smoke_pg       1129 non-null   float64
 15  delivery_mode          1171 non-null   float64
 16  sex                    1171 non-null   float64
 17  ga                     1171 non-null   float64
 18  stai_state_pw26        1114 non-null   float64
 19  stai_trait_pw26        1110 non-null   float64
 20  stai_state_m3          789 non-null    float64
 21  stai_trait_m3          770 non-null    float64
 22  epds_tot_pw26          1143 non-null   float64
 23  epds_tot_m3            782 non-null    float64
 24  infection_m3           1014 non-null   float64
 25  alcohol_pc             1171 non-null   float64
 26  alcohol_pg             1148 non-null   float64
 27  parity                 1172 non-null   float64
 28  weight_birth           1171 non-null   float64
 29  antibiotics_labour     1170 non-null   float64
 30  antibiotics_m3         1020 non-null   float64
 31  bisq_q3_m6             749 non-null    float64
 32  bisq_totslphrs_m6      742 non-null    float64
 33  bisq_q3_m12            551 non-null    float64
 34  bisq_totslphrs_m12     550 non-null    float64
 35  bf_m6                  1237 non-null   int64
 36  maternal_allergy_pw11  1202 non-null   float64
 37  cat                    758 non-null    float64
 38  dog                    763 non-null    float64
 39  expressway             755 non-null    float64
 40  allergy_cum            882 non-null    float64
 41  eczema_label           446 non-null    float64
 42  neopterin              978 non-null    float64
 43  riboflavin             978 non-null    float64
 44  nicotinicacid          978 non-null    float64
 45  trigonelline           978 non-null    float64
 46  pyridoxal              978 non-null    float64
 47  pyridoxalphosphate     978 non-null    float64
 48  vitamind3              942 non-null    float64
 49  arginine               978 non-null    float64
 50  adma                   978 non-null    float64
 51  creatine               978 non-null    float64
 52  cystathionine          978 non-null    float64
 53  m3histidine            978 non-null    float64
 54  histidine              978 non-null    float64
 55  methionine             978 non-null    float64
 56  hydroxyanthralinicac   978 non-null    float64
 57  kynurenicacid          978 non-null    float64
 58  kynurenine             978 non-null    float64
 59  tryptophan             978 non-null    float64
 60  betaine                978 non-null    float64
 61  choline                978 non-null    float64
 62  dimethylglycine        978 non-null    float64
 63  trimethylaminenoxide   978 non-null    float64
 64  cotinine               978 non-null    float64
 65  hydroxycotinine        978 non-null    float64
dtypes: float64(63), int64(2), object(1)
memory usage: 647.5+ KB

In [10]:
gusto_rhinitis_new = pd.merge(gusto_rhinitis_old, gusto_bevital, how='left', on='subject_id')
gusto_rhinitis_new.info()
gusto_rhinitis_new.to_csv('data/gusto_rhinitis_v3.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1237 entries, 0 to 1236
Data columns (total 66 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   subject_id             1237 non-null   object
 1   eczema_cum             752 non-null    float64
 2   rhinitis_cum           838 non-null    float64
 3   wheeze_cum             731 non-null    float64
 4   ethnicity              1237 non-null   int64
 5   delivery_age           1171 non-null   float64
 6   highest_edu12          1220 non-null   float64
 7   household_income       1152 non-null   float64
 8   pc_vig                 1168 non-null   float64
 9   pc_mvpa                1170 non-null   float64
 10  pg_vig                 1165 non-null   float64
 11  pg_mvpa                1167 non-null   float64
 12  smoking_pg             1168 non-null   float64
 13  passive_smoke_pc       1135 non-null   float64
 14  passive_smoke_pg       1129 non-null   float64
 15  delivery_mode          1171 non-null   float64
 16  sex                    1171 non-null   float64
 17  ga                     1171 non-null   float64
 18  stai_state_pw26        1114 non-null   float64
 19  stai_trait_pw26        1110 non-null   float64
 20  stai_state_m3          789 non-null    float64
 21  stai_trait_m3          770 non-null    float64
 22  epds_tot_pw26          1143 non-null   float64
 23  epds_tot_m3            782 non-null    float64
 24  infection_m3           1014 non-null   float64
 25  alcohol_pc             1171 non-null   float64
 26  alcohol_pg             1148 non-null   float64
 27  parity                 1172 non-null   float64
 28  weight_birth           1171 non-null   float64
 29  antibiotics_labour     1170 non-null   float64
 30  antibiotics_m3         1020 non-null   float64
 31  bisq_q3_m6             749 non-null    float64
 32  bisq_totslphrs_m6      742 non-null    float64
 33  bisq_q3_m12            551 non-null    float64
 34  bisq_totslphrs_m12     550 non-null    float64
 35  bf_m6                  1237 non-null   int64
 36  maternal_allergy_pw11  1202 non-null   float64
 37  cat                    758 non-null    float64
 38  dog                    763 non-null    float64
 39  expressway             755 non-null    float64
 40  allergy_cum            882 non-null    float64
 41  rhinitis_label         749 non-null    float64
 42  neopterin              978 non-null    float64
 43  riboflavin             978 non-null    float64
 44  nicotinicacid          978 non-null    float64
 45  trigonelline           978 non-null    float64
 46  pyridoxal              978 non-null    float64
 47  pyridoxalphosphate     978 non-null    float64
 48  vitamind3              942 non-null    float64
 49  arginine               978 non-null    float64
 50  adma                   978 non-null    float64
 51  creatine               978 non-null    float64
 52  cystathionine          978 non-null    float64
 53  m3histidine            978 non-null    float64
 54  histidine              978 non-null    float64
 55  methionine             978 non-null    float64
 56  hydroxyanthralinicac   978 non-null    float64
 57  kynurenicacid          978 non-null    float64
 58  kynurenine             978 non-null    float64
 59  tryptophan             978 non-null    float64
 60  betaine                978 non-null    float64
 61  choline                978 non-null    float64
 62  dimethylglycine        978 non-null    float64
 63  trimethylaminenoxide   978 non-null    float64
 64  cotinine               978 non-null    float64
 65  hydroxycotinine        978 non-null    float64
dtypes: float64(63), int64(2), object(1)
memory usage: 647.5+ KB

In [11]:
gusto_wheeze_new = pd.merge(gusto_wheeze_old, gusto_bevital, how='left', on='subject_id')
gusto_wheeze_new.info()
gusto_wheeze_new.to_csv('data/gusto_wheeze_v3.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1237 entries, 0 to 1236
Data columns (total 66 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   subject_id             1237 non-null   object
 1   eczema_cum             752 non-null    float64
 2   rhinitis_cum           838 non-null    float64
 3   wheeze_cum             731 non-null    float64
 4   ethnicity              1237 non-null   int64
 5   delivery_age           1171 non-null   float64
 6   highest_edu12          1220 non-null   float64
 7   household_income       1152 non-null   float64
 8   pc_vig                 1168 non-null   float64
 9   pc_mvpa                1170 non-null   float64
 10  pg_vig                 1165 non-null   float64
 11  pg_mvpa                1167 non-null   float64
 12  smoking_pg             1168 non-null   float64
 13  passive_smoke_pc       1135 non-null   float64
 14  passive_smoke_pg       1129 non-null   float64
 15  delivery_mode          1171 non-null   float64
 16  sex                    1171 non-null   float64
 17  ga                     1171 non-null   float64
 18  stai_state_pw26        1114 non-null   float64
 19  stai_trait_pw26        1110 non-null   float64
 20  stai_state_m3          789 non-null    float64
 21  stai_trait_m3          770 non-null    float64
 22  epds_tot_pw26          1143 non-null   float64
 23  epds_tot_m3            782 non-null    float64
 24  infection_m3           1014 non-null   float64
 25  alcohol_pc             1171 non-null   float64
 26  alcohol_pg             1148 non-null   float64
 27  parity                 1172 non-null   float64
 28  weight_birth           1171 non-null   float64
 29  antibiotics_labour     1170 non-null   float64
 30  antibiotics_m3         1020 non-null   float64
 31  bisq_q3_m6             749 non-null    float64
 32  bisq_totslphrs_m6      742 non-null    float64
 33  bisq_q3_m12            551 non-null    float64
 34  bisq_totslphrs_m12     550 non-null    float64
 35  bf_m6                  1237 non-null   int64
 36  maternal_allergy_pw11  1202 non-null   float64
 37  cat                    758 non-null    float64
 38  dog                    763 non-null    float64
 39  expressway             755 non-null    float64
 40  allergy_cum            882 non-null    float64
 41  wheeze_label           405 non-null    float64
 42  neopterin              978 non-null    float64
 43  riboflavin             978 non-null    float64
 44  nicotinicacid          978 non-null    float64
 45  trigonelline           978 non-null    float64
 46  pyridoxal              978 non-null    float64
 47  pyridoxalphosphate     978 non-null    float64
 48  vitamind3              942 non-null    float64
 49  arginine               978 non-null    float64
 50  adma                   978 non-null    float64
 51  creatine               978 non-null    float64
 52  cystathionine          978 non-null    float64
 53  m3histidine            978 non-null    float64
 54  histidine              978 non-null    float64
 55  methionine             978 non-null    float64
 56  hydroxyanthralinicac   978 non-null    float64
 57  kynurenicacid          978 non-null    float64
 58  kynurenine             978 non-null    float64
 59  tryptophan             978 non-null    float64
 60  betaine                978 non-null    float64
 61  choline                978 non-null    float64
 62  dimethylglycine        978 non-null    float64
 63  trimethylaminenoxide   978 non-null    float64
 64  cotinine               978 non-null    float64
 65  hydroxycotinine        978 non-null    float64
dtypes: float64(63), int64(2), object(1)
memory usage: 647.5+ KB

In [12]:
spresto_eczema_new = pd.merge(spresto_eczema_old, spresto_bevital, how='left', on='subject_id')
spresto_eczema_new.info()
spresto_eczema_new.to_csv('data/spresto_eczema_v3.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 379 entries, 0 to 378
Data columns (total 66 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   subject_id             379 non-null    int64
 1   eczema_cum             201 non-null    float64
 2   rhinitis_cum           239 non-null    float64
 3   wheeze_cum             176 non-null    float64
 4   ethnicity              376 non-null    float64
 5   delivery_age           365 non-null    float64
 6   highest_edu12          376 non-null    float64
 7   household_income       311 non-null    float64
 8   pc_vig                 375 non-null    float64
 9   pc_mvpa                375 non-null    float64
 10  pg_vig                 87 non-null     float64
 11  pg_mvpa                87 non-null     float64
 12  smoking_pg             349 non-null    float64
 13  passive_smoke_pc       365 non-null    float64
 14  passive_smoke_pg       349 non-null    float64
 15  delivery_mode          340 non-null    float64
 16  sex                    363 non-null    float64
 17  ga                     365 non-null    float64
 18  stai_state_pw26        299 non-null    float64
 19  stai_trait_pw26        299 non-null    float64
 20  stai_state_m3          218 non-null    float64
 21  stai_trait_m3          218 non-null    float64
 22  epds_tot_pw26          297 non-null    float64
 23  epds_tot_m3            218 non-null    float64
 24  infection_m3           312 non-null    float64
 25  alcohol_pc             376 non-null    float64
 26  alcohol_pg             349 non-null    float64
 27  parity                 375 non-null    float64
 28  weight_birth           348 non-null    float64
 29  antibiotics_labour     310 non-null    float64
 30  antibiotics_m3         316 non-null    float64
 31  bisq_q3_m6             170 non-null    float64
 32  bisq_totslphrs_m6      170 non-null    float64
 33  bisq_q3_m12            185 non-null    float64
 34  bisq_totslphrs_m12     185 non-null    float64
 35  bf_m6                  342 non-null    float64
 36  maternal_allergy_pw11  372 non-null    float64
 37  cat                    360 non-null    float64
 38  dog                    360 non-null    float64
 39  expressway             289 non-null    float64
 40  allergy_cum            269 non-null    float64
 41  eczema_label           140 non-null    float64
 42  neopterin              309 non-null    float64
 43  riboflavin             331 non-null    float64
 44  nicotinicacid          331 non-null    float64
 45  trigonelline           331 non-null    float64
 46  pyridoxal              331 non-null    float64
 47  pyridoxalphosphate     331 non-null    float64
 48  vitamind3              331 non-null    float64
 49  arginine               331 non-null    float64
 50  adma                   331 non-null    float64
 51  creatine               331 non-null    float64
 52  cystathionine          331 non-null    float64
 53  m3histidine            331 non-null    float64
 54  histidine              331 non-null    float64
 55  methionine             331 non-null    float64
 56  hydroxyanthralinicac   309 non-null    float64
 57  kynurenicacid          331 non-null    float64
 58  kynurenine             331 non-null    float64
 59  tryptophan             331 non-null    float64
 60  betaine                331 non-null    float64
 61  choline                331 non-null    float64
 62  dimethylglycine        331 non-null    float64
 63  trimethylaminenoxide   331 non-null    float64
 64  cotinine               331 non-null    float64
 65  hydroxycotinine        331 non-null    float64
dtypes: float64(65), int64(1)
memory usage: 198.4 KB

In [13]:
spresto_rhinitis_new = pd.merge(spresto_rhinitis_old, spresto_bevital, how='left', on='subject_id')
spresto_rhinitis_new.info()
spresto_rhinitis_new.to_csv('data/spresto_rhinitis_v3.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 379 entries, 0 to 378
Data columns (total 66 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   subject_id             379 non-null    int64
 1   eczema_cum             201 non-null    float64
 2   rhinitis_cum           239 non-null    float64
 3   wheeze_cum             176 non-null    float64
 4   ethnicity              376 non-null    float64
 5   delivery_age           365 non-null    float64
 6   highest_edu12          376 non-null    float64
 7   household_income       311 non-null    float64
 8   pc_vig                 375 non-null    float64
 9   pc_mvpa                375 non-null    float64
 10  pg_vig                 87 non-null     float64
 11  pg_mvpa                87 non-null     float64
 12  smoking_pg             349 non-null    float64
 13  passive_smoke_pc       365 non-null    float64
 14  passive_smoke_pg       349 non-null    float64
 15  delivery_mode          340 non-null    float64
 16  sex                    363 non-null    float64
 17  ga                     365 non-null    float64
 18  stai_state_pw26        299 non-null    float64
 19  stai_trait_pw26        299 non-null    float64
 20  stai_state_m3          218 non-null    float64
 21  stai_trait_m3          218 non-null    float64
 22  epds_tot_pw26          297 non-null    float64
 23  epds_tot_m3            218 non-null    float64
 24  infection_m3           312 non-null    float64
 25  alcohol_pc             376 non-null    float64
 26  alcohol_pg             349 non-null    float64
 27  parity                 375 non-null    float64
 28  weight_birth           348 non-null    float64
 29  antibiotics_labour     310 non-null    float64
 30  antibiotics_m3         316 non-null    float64
 31  bisq_q3_m6             170 non-null    float64
 32  bisq_totslphrs_m6      170 non-null    float64
 33  bisq_q3_m12            185 non-null    float64
 34  bisq_totslphrs_m12     185 non-null    float64
 35  bf_m6                  342 non-null    float64
 36  maternal_allergy_pw11  372 non-null    float64
 37  cat                    360 non-null    float64
 38  dog                    360 non-null    float64
 39  expressway             289 non-null    float64
 40  allergy_cum            269 non-null    float64
 41  rhinitis_label         217 non-null    float64
 42  neopterin              309 non-null    float64
 43  riboflavin             331 non-null    float64
 44  nicotinicacid          331 non-null    float64
 45  trigonelline           331 non-null    float64
 46  pyridoxal              331 non-null    float64
 47  pyridoxalphosphate     331 non-null    float64
 48  vitamind3              331 non-null    float64
 49  arginine               331 non-null    float64
 50  adma                   331 non-null    float64
 51  creatine               331 non-null    float64
 52  cystathionine          331 non-null    float64
 53  m3histidine            331 non-null    float64
 54  histidine              331 non-null    float64
 55  methionine             331 non-null    float64
 56  hydroxyanthralinicac   309 non-null    float64
 57  kynurenicacid          331 non-null    float64
 58  kynurenine             331 non-null    float64
 59  tryptophan             331 non-null    float64
 60  betaine                331 non-null    float64
 61  choline                331 non-null    float64
 62  dimethylglycine        331 non-null    float64
 63  trimethylaminenoxide   331 non-null    float64
 64  cotinine               331 non-null    float64
 65  hydroxycotinine        331 non-null    float64
dtypes: float64(65), int64(1)
memory usage: 198.4 KB

In [14]:
spresto_wheeze_new = pd.merge(spresto_wheeze_old, spresto_bevital, how='left', on='subject_id')
spresto_wheeze_new.info()
spresto_wheeze_new.to_csv('data/spresto_wheeze_v3.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 379 entries, 0 to 378
Data columns (total 66 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   subject_id             379 non-null    int64
 1   eczema_cum             201 non-null    float64
 2   rhinitis_cum           239 non-null    float64
 3   wheeze_cum             176 non-null    float64
 4   ethnicity              376 non-null    float64
 5   delivery_age           365 non-null    float64
 6   highest_edu12          376 non-null    float64
 7   household_income       311 non-null    float64
 8   pc_vig                 375 non-null    float64
 9   pc_mvpa                375 non-null    float64
 10  pg_vig                 87 non-null     float64
 11  pg_mvpa                87 non-null     float64
 12  smoking_pg             349 non-null    float64
 13  passive_smoke_pc       365 non-null    float64
 14  passive_smoke_pg       349 non-null    float64
 15  delivery_mode          340 non-null    float64
 16  sex                    363 non-null    float64
 17  ga                     365 non-null    float64
 18  stai_state_pw26        299 non-null    float64
 19  stai_trait_pw26        299 non-null    float64
 20  stai_state_m3          218 non-null    float64
 21  stai_trait_m3          218 non-null    float64
 22  epds_tot_pw26          297 non-null    float64
 23  epds_tot_m3            218 non-null    float64
 24  infection_m3           312 non-null    float64
 25  alcohol_pc             376 non-null    float64
 26  alcohol_pg             349 non-null    float64
 27  parity                 375 non-null    float64
 28  weight_birth           348 non-null    float64
 29  antibiotics_labour     310 non-null    float64
 30  antibiotics_m3         316 non-null    float64
 31  bisq_q3_m6             170 non-null    float64
 32  bisq_totslphrs_m6      170 non-null    float64
 33  bisq_q3_m12            185 non-null    float64
 34  bisq_totslphrs_m12     185 non-null    float64
 35  bf_m6                  342 non-null    float64
 36  maternal_allergy_pw11  372 non-null    float64
 37  cat                    360 non-null    float64
 38  dog                    360 non-null    float64
 39  expressway             289 non-null    float64
 40  allergy_cum            269 non-null    float64
 41  wheeze_label           84 non-null     float64
 42  neopterin              309 non-null    float64
 43  riboflavin             331 non-null    float64
 44  nicotinicacid          331 non-null    float64
 45  trigonelline           331 non-null    float64
 46  pyridoxal              331 non-null    float64
 47  pyridoxalphosphate     331 non-null    float64
 48  vitamind3              331 non-null    float64
 49  arginine               331 non-null    float64
 50  adma                   331 non-null    float64
 51  creatine               331 non-null    float64
 52  cystathionine          331 non-null    float64
 53  m3histidine            331 non-null    float64
 54  histidine              331 non-null    float64
 55  methionine             331 non-null    float64
 56  hydroxyanthralinicac   309 non-null    float64
 57  kynurenicacid          331 non-null    float64
 58  kynurenine             331 non-null    float64
 59  tryptophan             331 non-null    float64
 60  betaine                331 non-null    float64
 61  choline                331 non-null    float64
 62  dimethylglycine        331 non-null    float64
 63  trimethylaminenoxide   331 non-null    float64
 64  cotinine               331 non-null    float64
 65  hydroxycotinine        331 non-null    float64
dtypes: float64(65), int64(1)
memory usage: 198.4 KB

## add data to final cohort

In [39]:
final_cohort_old = pd.read_csv('./data/final_cohort.csv')
final_cohort_old['subject_id'].astype(object)
print(final_cohort_old.shape)
final_cohort_old.head()

(1151, 44)

,subject_id,eczema_cum,rhinitis_cum,wheeze_cum,ethnicity,delivery_age,highest_edu12,household_income,pc_vig,pc_mvpa,pg_vig,pg_mvpa,smoking_pg,passive_smoke_pc,passive_smoke_pg,delivery_mode,sex,ga,stai_state_pw26,stai_trait_pw26,stai_state_m3,stai_trait_m3,epds_tot_pw26,epds_tot_m3,infection_m3,alcohol_pc,alcohol_pg,parity,weight_birth,antibiotics_labour,antibiotics_m3,bisq_q3_m6,bisq_totslphrs_m6,bisq_q3_m12,bisq_totslphrs_m12,bf_m6,maternal_allergy_pw11,cat,dog,expressway,allergy_cum,eczema_label,rhinitis_label,wheeze_label
0,010-21613,0.0,0.0,0.0,1.0,35.94,1.0,3.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,40.29,26.0,35.0,26.0,29.0,3.0,0.0,0.0,0.0,0.0,1.0,3.180,0.0,0.0,10.0,11.5,10.0,11.0,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0
1,010-22012,1.0,1.0,1.0,1.0,32.54,1.0,3.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,36.29,45.0,52.0,52.0,50.0,9.0,14.0,0.0,0.0,0.0,0.0,2.598,1.0,0.0,4.0,6.0,10.0,12.0,0.0,1.0,0.0,0.0,0.0,1,1.0,1.0,1.0
2,019-30361,NaN,1.0,NaN,1.0,35.91,1.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,37.71,37.0,37.0,NaN,NaN,3.0,NaN,NaN,0.0,0.0,0.0,2.970,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1,NaN,1.0,NaN
3,020-66135,1.0,1.0,0.0,1.0,30.25,1.0,5.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,40.29,51.0,51.0,30.0,32.0,10.0,4.0,1.0,1.0,0.0,0.0,3.850,1.0,0.0,6.0,10.0,10.0,12.0,1.0,1.0,1.0,0.0,0.0,1,1.0,1.0,NaN
4,010-21410,1.0,0.0,0.0,2.0,40.00,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,39.14,26.0,34.0,NaN,NaN,8.0,NaN,0.0,0.0,0.0,3.0,3.775,1.0,0.0,3.5,5.5,4.5,7.5,0.0,0.0,0.0,0.0,0.0,1,1.0,NaN,NaN

In [41]:
final_cohort_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1151 entries, 0 to 1150
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   subject_id             1151 non-null   object
 1   eczema_cum             929 non-null    float64
 2   rhinitis_cum           1068 non-null   float64
 3   wheeze_cum             894 non-null    float64
 4   ethnicity              1151 non-null   float64
 5   delivery_age           1151 non-null   float64
 6   highest_edu12          1141 non-null   float64
 7   household_income       1047 non-null   float64
 8   pc_vig                 1135 non-null   float64
 9   pc_mvpa                1137 non-null   float64
 10  pg_vig                 943 non-null    float64
 11  pg_mvpa                945 non-null    float64
 12  smoking_pg             1131 non-null   float64
 13  passive_smoke_pc       1101 non-null   float64
 14  passive_smoke_pg       1099 non-null   float64
 15  delivery_mode          1136 non-null   float64
 16  sex                    1150 non-null   float64
 17  ga                     1151 non-null   float64
 18  stai_state_pw26        1055 non-null   float64
 19  stai_trait_pw26        1053 non-null   float64
 20  stai_state_m3          833 non-null    float64
 21  stai_trait_m3          817 non-null    float64
 22  epds_tot_pw26          1071 non-null   float64
 23  epds_tot_m3            828 non-null    float64
 24  infection_m3           1094 non-null   float64
 25  alcohol_pc             1140 non-null   float64
 26  alcohol_pg             1114 non-null   float64
 27  parity                 1150 non-null   float64
 28  weight_birth           1143 non-null   float64
 29  antibiotics_labour     1113 non-null   float64
 30  antibiotics_m3         1100 non-null   float64
 31  bisq_q3_m6             785 non-null    float64
 32  bisq_totslphrs_m6      779 non-null    float64
 33  bisq_q3_m12            644 non-null    float64
 34  bisq_totslphrs_m12     643 non-null    float64
 35  bf_m6                  1150 non-null   float64
 36  maternal_allergy_pw11  1120 non-null   float64
 37  cat                    921 non-null    float64
 38  dog                    925 non-null    float64
 39  expressway             872 non-null    float64
 40  allergy_cum            1151 non-null   int64
 41  eczema_label           586 non-null    float64
 42  rhinitis_label         966 non-null    float64
 43  wheeze_label           489 non-null    float64
dtypes: float64(42), int64(1), object(1)
memory usage: 395.8+ KB

In [17]:
bevital = pd.concat([gusto_bevital, spresto_bevital], axis=0, sort=False)
bevital.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2277 entries, 0 to 984
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   subject_id            2277 non-null   object
 1   neopterin             1295 non-null   float64
 2   riboflavin            1317 non-null   float64
 3   nicotinicacid         1317 non-null   float64
 4   trigonelline          1317 non-null   float64
 5   pyridoxal             1317 non-null   float64
 6   pyridoxalphosphate    1317 non-null   float64
 7   vitamind3             1281 non-null   float64
 8   arginine              1317 non-null   float64
 9   adma                  1317 non-null   float64
 10  creatine              1317 non-null   float64
 11  cystathionine         1317 non-null   float64
 12  m3histidine           1317 non-null   float64
 13  histidine             1317 non-null   float64
 14  methionine            1317 non-null   float64
 15  hydroxyanthralinicac  1295 non-null   float64
 16  kynurenicacid         1317 non-null   float64
 17  kynurenine            1317 non-null   float64
 18  tryptophan            1317 non-null   float64
 19  betaine               1317 non-null   float64
 20  choline               1317 non-null   float64
 21  dimethylglycine       1317 non-null   float64
 22  trimethylaminenoxide  1317 non-null   float64
 23  cotinine              1317 non-null   float64
 24  hydroxycotinine       1317 non-null   float64
dtypes: float64(24), object(1)
memory usage: 462.5+ KB

In [18]:
len(bevital['subject_id'].unique())

2277

In [42]:
final_cohort_new = pd.merge(final_cohort_old, bevital, how='left', on='subject_id')
final_cohort_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1151 entries, 0 to 1150
Data columns (total 68 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   subject_id             1151 non-null   object
 1   eczema_cum             929 non-null    float64
 2   rhinitis_cum           1068 non-null   float64
 3   wheeze_cum             894 non-null    float64
 4   ethnicity              1151 non-null   float64
 5   delivery_age           1151 non-null   float64
 6   highest_edu12          1141 non-null   float64
 7   household_income       1047 non-null   float64
 8   pc_vig                 1135 non-null   float64
 9   pc_mvpa                1137 non-null   float64
 10  pg_vig                 943 non-null    float64
 11  pg_mvpa                945 non-null    float64
 12  smoking_pg             1131 non-null   float64
 13  passive_smoke_pc       1101 non-null   float64
 14  passive_smoke_pg       1099 non-null   float64
 15  delivery_mode          1136 non-null   float64
 16  sex                    1150 non-null   float64
 17  ga                     1151 non-null   float64
 18  stai_state_pw26        1055 non-null   float64
 19  stai_trait_pw26        1053 non-null   float64
 20  stai_state_m3          833 non-null    float64
 21  stai_trait_m3          817 non-null    float64
 22  epds_tot_pw26          1071 non-null   float64
 23  epds_tot_m3            828 non-null    float64
 24  infection_m3           1094 non-null   float64
 25  alcohol_pc             1140 non-null   float64
 26  alcohol_pg             1114 non-null   float64
 27  parity                 1150 non-null   float64
 28  weight_birth           1143 non-null   float64
 29  antibiotics_labour     1113 non-null   float64
 30  antibiotics_m3         1100 non-null   float64
 31  bisq_q3_m6             785 non-null    float64
 32  bisq_totslphrs_m6      779 non-null    float64
 33  bisq_q3_m12            644 non-null    float64
 34  bisq_totslphrs_m12     643 non-null    float64
 35  bf_m6                  1150 non-null   float64
 36  maternal_allergy_pw11  1120 non-null   float64
 37  cat                    921 non-null    float64
 38  dog                    925 non-null    float64
 39  expressway             872 non-null    float64
 40  allergy_cum            1151 non-null   int64
 41  eczema_label           586 non-null    float64
 42  rhinitis_label         966 non-null    float64
 43  wheeze_label           489 non-null    float64
 44  neopterin              776 non-null    float64
 45  riboflavin             776 non-null    float64
 46  nicotinicacid          776 non-null    float64
 47  trigonelline           776 non-null    float64
 48  pyridoxal              776 non-null    float64
 49  pyridoxalphosphate     776 non-null    float64
 50  vitamind3              747 non-null    float64
 51  arginine               776 non-null    float64
 52  adma                   776 non-null    float64
 53  creatine               776 non-null    float64
 54  cystathionine          776 non-null    float64
 55  m3histidine            776 non-null    float64
 56  histidine              776 non-null    float64
 57  methionine             776 non-null    float64
 58  hydroxyanthralinicac   776 non-null    float64
 59  kynurenicacid          776 non-null    float64
 60  kynurenine             776 non-null    float64
 61  tryptophan             776 non-null    float64
 62  betaine                776 non-null    float64
 63  choline                776 non-null    float64
 64  dimethylglycine        776 non-null    float64
 65  trimethylaminenoxide   776 non-null    float64
 66  cotinine               776 non-null    float64
 67  hydroxycotinine        776 non-null    float64
dtypes: float64(66), int64(1), object(1)
memory usage: 620.5+ KB

In [44]:
final_cohort_new.to_csv('data/final_cohort_v3.csv', index=False)

In [ ]:
spresto_wheeze_new = pd.merge(spresto_wheeze_old, spresto_bevital, how='left', on='subject_id')
spresto_wheeze_new.info()
spresto_wheeze_new.to_csv('data/spresto_wheeze_v3.csv', index=False)

## add new data to excluded patients

In [7]:
excluded_old = pd.read_csv('./data/excluded_patients.csv')
print(excluded_old.shape)
excluded_old.head()

(465, 44)

,subject_id,eczema_cum,rhinitis_cum,wheeze_cum,ethnicity,delivery_age,highest_edu12,household_income,pc_vig,pc_mvpa,pg_vig,pg_mvpa,smoking_pg,passive_smoke_pc,passive_smoke_pg,delivery_mode,sex,ga,stai_state_pw26,stai_trait_pw26,stai_state_m3,stai_trait_m3,epds_tot_pw26,epds_tot_m3,infection_m3,alcohol_pc,alcohol_pg,parity,weight_birth,antibiotics_labour,antibiotics_m3,bisq_q3_m6,bisq_totslphrs_m6,bisq_q3_m12,bisq_totslphrs_m12,bf_m6,maternal_allergy_pw11,cat,dog,expressway,allergy_cum,eczema_label,rhinitis_label,wheeze_label
0,020-08047,0.0,0.0,NaN,3.0,30.89,1.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,39.86,26.0,28.0,22.0,29.0,4.0,2.0,0.0,0.0,0.0,0.0,3.365,1.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
1,010-20458,NaN,NaN,NaN,1.0,NaN,1.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10951,NaN,NaN,NaN,1.0,29.27,1.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,0.0,2.0,0.0,38.14,21.0,24.0,NaN,NaN,0.0,NaN,NaN,1.0,0.0,0.0,2.976,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,010-21219,NaN,NaN,NaN,1.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,010-20433,0.0,NaN,NaN,1.0,31.40,1.0,4.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,2.0,1.0,38.00,23.0,29.0,48.0,51.0,6.0,9.0,0.0,1.0,0.0,0.0,2.885,1.0,0.0,9.5,12.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN

In [19]:
bevital

,subject_id,neopterin,riboflavin,nicotinicacid,trigonelline,pyridoxal,pyridoxalphosphate,vitamind3,arginine,adma,creatine,cystathionine,m3histidine,histidine,methionine,hydroxyanthralinicac,kynurenicacid,kynurenine,tryptophan,betaine,choline,dimethylglycine,trimethylaminenoxide,cotinine,hydroxycotinine
0,010-04002,15.6,23.80,0.00,0.2820,13.1,55.4,72.00,25.3,0.384,41.4,0.215,0.397,51.3,14.8,61.1,12.4,1.110,44.1,9.23,9.31,1.38,0.808,8.59,0.0
1,010-04004,27.7,6.24,0.00,0.3290,13.1,47.2,45.00,25.1,0.359,33.5,0.125,1.160,41.1,11.8,94.9,11.9,1.210,33.2,19.30,11.10,1.69,13.600,0.00,0.0
2,010-04006,32.4,9.92,0.00,0.4860,35.3,138.0,98.00,31.1,0.483,41.4,0.116,0.278,75.5,14.9,69.6,30.4,1.370,41.5,9.15,9.42,1.74,1.240,0.00,0.0
3,010-04010,12.3,17.30,0.00,0.1830,186.0,191.0,131.00,56.3,0.365,62.5,0.189,21.200,70.1,28.4,58.8,11.7,0.737,48.4,12.50,6.52,1.61,6.220,0.00,0.0
4,010-04011,19.8,12.00,0.00,0.0539,30.4,146.0,107.00,21.8,0.336,48.6,0.112,1.920,57.7,12.5,72.8,12.8,0.976,46.7,16.90,8.89,1.39,0.724,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,11051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
981,11052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
982,11053,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
983,11054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
984,11056,17.9,23.10,0.77,0.1700,58.4,168.0,64.27,35.4,0.480,48.6,0.070,1.810,66.8,19.0,84.4,22.6,1.080,48.4,12.00,8.21,1.92,2.510,0.00,0.0

In [20]:
excluded_new = pd.merge(excluded_old, bevital, how='left', on='subject_id')
excluded_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 465 entries, 0 to 464
Data columns (total 68 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   subject_id             465 non-null    object
 1   eczema_cum             24 non-null     float64
 2   rhinitis_cum           9 non-null      float64
 3   wheeze_cum             13 non-null     float64
 4   ethnicity              462 non-null    float64
 5   delivery_age           385 non-null    float64
 6   highest_edu12          455 non-null    float64
 7   household_income       416 non-null    float64
 8   pc_vig                 408 non-null    float64
 9   pc_mvpa                408 non-null    float64
 10  pg_vig                 309 non-null    float64
 11  pg_mvpa                309 non-null    float64
 12  smoking_pg             386 non-null    float64
 13  passive_smoke_pc       399 non-null    float64
 14  passive_smoke_pg       379 non-null    float64
 15  delivery_mode          375 non-null    float64
 16  sex                    384 non-null    float64
 17  ga                     385 non-null    float64
 18  stai_state_pw26        358 non-null    float64
 19  stai_trait_pw26        356 non-null    float64
 20  stai_state_m3          174 non-null    float64
 21  stai_trait_m3          171 non-null    float64
 22  epds_tot_pw26          369 non-null    float64
 23  epds_tot_m3            172 non-null    float64
 24  infection_m3           232 non-null    float64
 25  alcohol_pc             407 non-null    float64
 26  alcohol_pg             383 non-null    float64
 27  parity                 397 non-null    float64
 28  weight_birth           376 non-null    float64
 29  antibiotics_labour     367 non-null    float64
 30  antibiotics_m3         236 non-null    float64
 31  bisq_q3_m6             134 non-null    float64
 32  bisq_totslphrs_m6      133 non-null    float64
 33  bisq_q3_m12            92 non-null     float64
 34  bisq_totslphrs_m12     92 non-null     float64
 35  bf_m6                  429 non-null    float64
 36  maternal_allergy_pw11  454 non-null    float64
 37  cat                    197 non-null    float64
 38  dog                    198 non-null    float64
 39  expressway             172 non-null    float64
 40  allergy_cum            0 non-null      float64
 41  eczema_label           0 non-null      float64
 42  rhinitis_label         0 non-null      float64
 43  wheeze_label           0 non-null      float64
 44  neopterin              202 non-null    float64
 45  riboflavin             202 non-null    float64
 46  nicotinicacid          202 non-null    float64
 47  trigonelline           202 non-null    float64
 48  pyridoxal              202 non-null    float64
 49  pyridoxalphosphate     202 non-null    float64
 50  vitamind3              195 non-null    float64
 51  arginine               202 non-null    float64
 52  adma                   202 non-null    float64
 53  creatine               202 non-null    float64
 54  cystathionine          202 non-null    float64
 55  m3histidine            202 non-null    float64
 56  histidine              202 non-null    float64
 57  methionine             202 non-null    float64
 58  hydroxyanthralinicac   202 non-null    float64
 59  kynurenicacid          202 non-null    float64
 60  kynurenine             202 non-null    float64
 61  tryptophan             202 non-null    float64
 62  betaine                202 non-null    float64
 63  choline                202 non-null    float64
 64  dimethylglycine        202 non-null    float64
 65  trimethylaminenoxide   202 non-null    float64
 66  cotinine               202 non-null    float64
 67  hydroxycotinine        202 non-null    float64
dtypes: float64(67), object(1)
memory usage: 250.7+ KB

In [21]:
excluded_new.to_csv('data/excluded_v3.csv', index=False)